# Generated by Django 3.0.4 on 2020-12-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0023_auto_20201210_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[(1, 'Online'), (0, 'Offline')], default=0, max_length=1, null=True)),
                ('status', models.BooleanField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('description', models.TextField(blank=True, help_text='Reason of Activate or Inactivate of method', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=7, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('sold_number', models.IntegerField(blank=True, default=0, null=True)),
                ('img_url', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(blank=True, default=1, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=8, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Member')),
            ],
        ),
    ]
