# Generated by Django 3.0.4 on 2020-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201211_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
