# Generated by Django 3.0.4 on 2020-12-10 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default="It's a test text for About Us.", help_text="Please Enter 'About Us' Text Here.")),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(help_text='Enter Here Question', max_length=1500)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default="It's a test text For Field Description.", help_text='Please Enter Field Description Text Here.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('join_date', models.DateField(default=datetime.datetime(2020, 12, 10, 8, 2, 2, 555431, tzinfo=utc))),
                ('role', models.CharField(choices=[('A', 'Administrator'), ('C', 'Client')], default='C', max_length=1)),
                ('level', models.CharField(choices=[('b', 'Beginner'), ('m', 'Middle'), ('p', 'professional')], default='b', max_length=1)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
        migrations.CreateModel(
            name='CoursesInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(blank=True, choices=[('EV', 'Every Days'), ('E', 'Even Days'), ('O', 'Odd Days')], max_length=2, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Field')),
            ],
            options={
                'ordering': ['class_day'],
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 12, 10, 8, 2, 2, 557428, tzinfo=utc))),
                ('place', models.CharField(max_length=100)),
                ('competition_date', models.DateField()),
                ('position', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=100)),
                ('tournament', models.CharField(choices=[('P', 'Provincial'), ('N', 'National'), ('C', 'Continental'), ('G', 'Global')], max_length=300)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Field')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
