# Generated by Django 3.0.4 on 2020-12-10 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 10, 8, 5, 45, 1573, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 5, 44, 999578, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(blank=True, choices=[('b', 'Beginner'), ('m', 'Middle'), ('p', 'professional')], default='b', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Administrator'), ('C', 'Client')], default='C', max_length=1, null=True),
        ),
    ]
