# Generated by Django 3.0.4 on 2020-12-10 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20201210_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='competition_date',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, default="It's a test text for About Us.", help_text="Please Enter 'About Us' Text Here.", null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 10, 5, 691444, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Field'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='tournament',
            field=models.CharField(blank=True, choices=[('P', 'Provincial'), ('N', 'National'), ('C', 'Continental'), ('G', 'Global')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 8, 10, 5, 692440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='text',
            field=models.TextField(blank=True, help_text='Enter Here Question', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 10, 5, 689449, tzinfo=utc), null=True),
        ),
    ]
