# Generated by Django 3.0.4 on 2020-12-10 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20201210_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 12, 47, 244424, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 8, 12, 47, 245421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 12, 47, 243427, tzinfo=utc), null=True),
        ),
    ]
