# Generated by Django 3.0.4 on 2020-12-10 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20201210_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, help_text='Enter Here Question', max_length=1500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 8, 19, 21, 25292, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.AlterField(
            model_name='championship',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 19, 21, 24295, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 19, 21, 22301, tzinfo=utc), null=True),
        ),
    ]
